sudo: false

language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_c691d423ede5_key -iv $encrypted_c691d423ede5_iv -in rft-math.pem.enc -out rft-math.pem -d
  - chmod 400 rft-math.pem
  - ssh-agent $eval

install:
  - eval `ssh-agent -s`
  - bash deploy.sh

after_install:
  - ssh-agent -k

notifications:
  email:
    recipients:
      - levivig@gmail.com
    on_success: never # default: change
    on_failure: always # default: always