sudo: false

language: python

install:
  - echo Install

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c691d423ede5_key -iv $encrypted_c691d423ede5_iv -in rft-math.pem.enc -out rft-math.pem -d
  - chmod 400 rft-math.pem

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master

notifications:
  email:
    recipients:
      - levivig@gmail.com
    on_success: never # default: change
    on_failure: always # default: always