version: '3'

services:
  web:
    build: .
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
    - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: postgres
    environment:
      POSTGRES_DB: rft
      POSTGRES_USER: rft
      POSTGRES_PASSWORD: tokmindegy
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080