version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - add_ssh_keys:
          fingerprints:
            - "45:76:c5:72:66:1e:68:dc:f7:eb:cd:5a:42:e8:7f:d6"

# These commands are triggered only after a successful (green) build.
 deployment:
   master:
      branch: master
        commands:
          - ssh ec2-user@ec2-3-16-89-127.us-east-2.compute.amazonaws.com 'cd /home/ec2-user/math_backend && git pull origin master'
