# Generated by Django 2.1.2 on 2018-11-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.IntegerField()),
                ('question', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
