# Generated by Django 2.1.2 on 2018-12-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
