# Generated by Django 2.1.2 on 2018-11-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
