# Generated by Django 2.1.2 on 2018-12-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_results_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='username',
            new_name='name',
        ),
    ]
