# Generated by Django 2.1.2 on 2018-12-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20181204_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='results',
            name='time',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='results',
            name='type',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
