# Generated by Django 2.1.2 on 2018-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20181204_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.IntegerField(),
        ),
    ]
