# Generated by Django 2.1.2 on 2018-12-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20181204_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='results',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='type',
            field=models.IntegerField(),
        ),
    ]
